spring:
  #配置数据库以及Druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@//39.107.244.199/MRES
    username: MRESTest
    password: MRESTest
    driver-class-name: oracle.jdbc.driver.OracleDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  #配置JPA
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  #配置日志
  logging:
    config: classpath:log4j2.yml
#    level:
#      com.tjpld.gis: 'info'


